export default {
  danmu: {
    show_medal: false,
    user_text_size: 12,
    danmu_text_size: 14,
    user_color: "#56F0F5FF",
    danmu_color: "#F8BEFFFF",
    show_time: true,
    next_line: true,
    show_user: false,
    time_text_size: 12,
    danmu_head_size: 36,
    time_color: "#90D1FFFF",
  },
  gift: {
    hidden: false,
    show_medal: false,
    user_text_size: 12,
    danmu_text_size: 12,
    user_color: "#FF9090FF",
    danmu_color: "#F76A13FF",
  },
  interact: {
    hidden: false,
    show_medal: true,
    user_text_size: 12,
    danmu_text_size: 12,
    user_color: "#FF9494FF",
    danmu_color: "#FF92FFFF",
  },
  apperance: {
    transparent: false,
    background: "#000000BD",
  },
  setting: {
    transparent: false,
    background: "#D5E7EB",
    blur: false,
    color: "#000000",
    size: 12,
  },
  shield: {
    list: [],
    level: 0,
  },
} as Setting
